apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: staging-deploy
  template:
    metadata:
      labels:
        app: staging-deploy
    spec:
      containers:
        - name: hello
          image: namnguyen2307/index
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: staging-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: staging-deploy

